#!/bin/bash

cd "$(dirname "$0")"

cleanup()
{
    if [[ -e "$tmp" ]]; then
        rm -r "$tmp"
    fi
}
trap cleanup EXIT

# BSD mktemp syntax.
tmp=$(mktemp -d /var/tmp/"$(basename "$0")".XXXXXX)

echo "Pulling macports-ports"
git clone --recursive https://github.com/macports/macports-ports $tmp/macports-ports
macports_ports_commit="$(git -C $tmp/macports-ports rev-parse HEAD)"
# Recursively delete .git and .gitmodules files inside macports-ports (currently it doesn't have any but its good incase for some reason this changes to be consistent).
find "$tmp/macports-ports" -name .git -exec rm -rf {} +
find "$tmp/macports-ports" -name .gitmodules -exec rm -f {} +
mv $tmp/macports-ports/README.md macports-ports-readme.md

echo "Pulling github.com/alex-free/powerpc-ports tigerports branch"
git clone -b tigerports --recursive https://github.com/alex-free/powerpc-ports $tmp/powerpc-ports
powerpc_ports_commit="$(git -C $tmp/powerpc-ports rev-parse HEAD)"
mv $tmp/powerpc-ports/README.md powerpc-ports-readme.md
# Recursively delete .git and .gitmodules files inside powerpc-ports.
find "$tmp/powerpc-ports" -name .git -exec rm -rf {} +
find "$tmp/powerpc-ports" -name .gitmodules -exec rm -f {} +

# Nuke everything currently in this repo except these files:
find . -maxdepth 1 ! \( -name . -o -name .git -o -name merge -o -name powerpc-ports-readme.md -o -name macports-ports-readme.md \) -exec rm -rf {} +

# Dump it into this repo.
mv $tmp/macports-ports/* .
cp -r $tmp/powerpc-ports/* .

# Gen readme.md
echo -e "This is the TigerPorts Ports Tree for http://tigerports.com\n\nLast updated on $(date).\n\nThis consists of a combination of 2 git repos as upstream:\n\n[https://github.com/macports/macports-ports](https://github.com/macports/macports-ports) at commit: $macports_ports_commit.\n\n[https://github.com/alex-free/powerpc-ports/tree/tigerports](https://github.com/alex-free/powerpc-ports/tree/tigerports) at commit: $powerpc_ports_commit.\n\nSuggest improvements, contribute, and open issues at [my fork of powerpc-ports in the tigerports branch](https://github.com/alex-free/powerpc-ports/tree/tigerports)." > readme.md
